spring.application.name=gestao-de-eventos

#config para subir aplicação sem ter banco de dados configurado
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration