info.app.name=@project.name@
info.app.description=@project.description@
info.app.version=@project.version@

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

spring.application.name=gestao-de-eventos

spring.datasource.url=jdbc:postgresql://localhost:5432/gestaodeeventosdb
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#config para subir aplicação sem ter banco de dados configurado
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration